site_name: de.systopia.assumedpayments
site_description: FIXME
site_author: FIXME
repo_url: https://FIXME

theme:
  name: material

nav:
  - Introduction: index.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
